### ISSUE TITLE
F-Droid / IzzyOnDroid repo?

### ISSUE THREAD

**Issue by zyxmdvs** [trakt/showly#474]
Could this app be released on the F-Droid repository? I know that there's some work that needs to be done in order for that to happen, so that may be out of the question for now. Would it be possible to put showly 2.0 in the IzzyOnDroid repository instead? Thanks for considering!

**Comment by zyxmdvs** [comment]
Izzy seems to be okay with this, as seen here. https://github.com/michaldrabik/showly-2.0/issues/46

**Comment by rollingmoai** [comment]
Duplicate if #46, please close this issue.
